FROM nginx:latest as production

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE $SERVER_PORT
CMD [ "nginx", "-g", "daemon off;" ]
